import { AiFillStar } from "react-icons/ai";
import img1 from '../../assets/vision.jpg';

const data = [
  {
    img: "../../assets/vision.jpg",
    title: "Dr. Sreenivasan R    ",
    reviews: "MBBS-General Medicine, MD-General Medicine    ",
    prevPrice: "19 years",
    newPrice: "Rs. 500",
    category: "General Physician",
    exp: "19 years",
  },
  {
    img: "",
    title: "Dr. Nagaraj P    ",
    reviews: "MBBS-General Medicine    ",
    prevPrice: "7 years",
    newPrice: "Rs. 350",
    category: "General Physician",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Sudha Vinod Menon    ",
    reviews: "MBBS-General Medicine    ",
    prevPrice: "40 years",
    newPrice: "Rs. 950",
    category: "General Physician",
    exp: "40 years",
  },
  {
    img: "",
    title: "Dr. Renu Saraogi    ",
    reviews: "MBBS-General Medicine    ",
    prevPrice: "23 years",
    newPrice: "Rs. 600",
    category: "General Physician",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "General Physician",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Vinu N    ",
    reviews: "MBBS-General Medicine, MD-Paediatrics, DNB-Paediatrics    ",
    prevPrice: "13 years",
    newPrice: "Rs. 2000",
    category: "Pediatrics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Khalilur Rehman Gajula    ",
    reviews: "MBBS-General Medicine, MD-Paediatrics, Fellowship-Paediatric Neonatology    ",
    prevPrice: "6 years",
    newPrice: "Rs. 450",
    category: "Pediatrics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Lokesh    ",
    reviews: "MBBS-General Medicine, Diploma-Paediatrics    ",
    prevPrice: "15 years",
    newPrice: "Rs. 550",
    category: "Pediatrics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Rajiv Aggarwal    ",
    reviews: "MBBS-General Medicine, MD-Paediatrics    ",
    prevPrice: "22 years",
    newPrice: "Rs. 350",
    category: "Pediatrics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Rashmi Jeenakeri    ",
    reviews: "MBBS-General Medicine, DNB-Paediatrics    ",
    prevPrice: "17 years",
    newPrice: "Rs. 350",
    category: "Pediatrics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Mridula Radhakrishnan    ",
    reviews: "BDS-Dental, MDS-Implantologist    ",
    prevPrice: "16 years",
    newPrice: "Rs. 350",
    category: "Dental",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Chiranjeevi Reddy G    ",
    reviews: "BDS-Dental, MDS-Implantologist    ",
    prevPrice: "23 years",
    newPrice: "Rs. 300",
    category: "Dental",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Syed Ghouse    ",
    reviews: "BDS-Dental    ",
    prevPrice: "13 years",
    newPrice: "Rs. 350",
    category: "Dental",
    exp: "7 years",
  },
  
  {
    img: "",
    title: "Dr. Sreenivasan R    ",
    reviews: "MBBS-General Medicine, MD-General Medicine    ",
    prevPrice: "19 years",
    newPrice: "Rs. 350",
    category: "Cold and Fever",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Nagaraj P    ",
    reviews: "MBBS-General Medicine    ",
    prevPrice: "7 years",
    newPrice: "Rs. 350",
    category: "Cold and Fever",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Sudha Vinod Menon    ",
    reviews: "MBBS-General Medicine    ",
    prevPrice: "40 years",
    newPrice: "Rs. 350",
    category: "Cold and Fever",
    exp: "7 years",
  },
  
  {
    img: "",
    title: "Dr. Shobha Sudeep    ",
    reviews: "MBBS-General Medicine, Diploma-Dermatology    ",
    prevPrice: "8 years",
    newPrice: "Rs. 350",
    category: "Dermatology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Deepak Devakar    ",
    reviews: "MBBS-General Medicine, Diploma-Dermatology, Venereology and Leprosy    ",
    prevPrice: "18 years",
    newPrice: "Rs. 350",
    category: "Dermatology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Rashmi S    ",
    reviews: "MBBS-General Medicine, MD-Dermatology, Diploma-Dermatology    ",
    prevPrice: "16 years",
    newPrice: "Rs. 350",
    category: "Dermatology",
    exp: "7 years",
  },
  
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Sexology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Sexology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Sexology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Sexology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Sexology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gynecology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gynecology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gynecology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gynecology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gynecology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "General Surgery",
    exp: "7 years",
  },

  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "General Surgery",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "General Surgery",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "General Surgery",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "General Surgery",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Lab Report Analysis",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Lab Report Analysis",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Lab Report Analysis",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Lab Report Analysis",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Lab Report Analysis",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gastroenterology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gastroenterology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gastroenterology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gastroenterology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Gastroenterology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Orthopedics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Orthopedics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Orthopedics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Orthopedics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Orthopedics",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Pregnancy Issues",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Pregnancy Issues",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Pregnancy Issues",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Pregnancy Issues",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Pregnancy Issues",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Ear Nose and Throat",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Ear Nose and Throat",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Ear Nose and Throat",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Ear Nose and Throat",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Ear Nose and Throat",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Neurology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Neurology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Neurology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Neurology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Neurology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychiatry",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychiatry",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychiatry",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychiatry",
    exp: "7 years",
  },
  
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychiatry",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Hair Scalp Care",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Hair Scalp Care",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Hair Scalp Care",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Hair Scalp Care",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Hair Scalp Care",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychology",
    exp: "7 years",
  },
  {
    img: "",
    title: "Dr. Reddy K V S    ",
    reviews: "MBBS-General Medicine, MD - General Medicine    ",
    prevPrice: "28 years",
    newPrice: "Rs. 800",
    category: "Psychology",
    exp: "7 years",
  },
]

export default data;